spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.hkzjqmbnmxlcpcxalqei
spring.datasource.password=Ac09162961807
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=change_this_to_a_long_random_string_at_least_32_chars
app.jwt.expiration-ms=3600000

server.port=8080