spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${ACCESS_TOKEN_EXPIRATION:3600000}
app.frontend-url=${FRONTEND_URL}
app.admin.enabled=${ADMIN_CREATE:false}
app.admin.email=${ADMIN_EMAIL:admin@stockmate.com}
app.admin.password=${ADMIN_PASSWORD:}
